//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SIRModel", "FK_IncidentAuditItem_AuditItem", "AuditItem", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SIRModel.AuditItem), "IncidentAuditItem", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SIRModel.IncidentAuditItem))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SIRModel", "FK_IncidentAuditItem_Incident", "Incident", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SIRModel.Incident), "IncidentAuditItem", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SIRModel.IncidentAuditItem))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SIRModel", "FK_OtherAuditItem_Incident", "Incident", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SIRModel.Incident), "OtherAuditItem", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SIRModel.OtherAuditItem))]

// Original file name:
// Generation date: 3/3/2009 10:04:39 AM
namespace SIRModel
{
    
    /// <summary>
    /// There are no comments for SIREntities in the schema.
    /// </summary>
    public partial class SIREntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new SIREntities object using the connection string found in the 'SIREntities' section of the application configuration file.
        /// </summary>
        public SIREntities() : 
                base("name=SIREntities", "SIREntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new SIREntities object.
        /// </summary>
        public SIREntities(string connectionString) : 
                base(connectionString, "SIREntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new SIREntities object.
        /// </summary>
        public SIREntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "SIREntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for AuditItem in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<AuditItem> AuditItem
        {
            get
            {
                if ((this._AuditItem == null))
                {
                    this._AuditItem = base.CreateQuery<AuditItem>("[AuditItem]");
                }
                return this._AuditItem;
            }
        }
        private global::System.Data.Objects.ObjectQuery<AuditItem> _AuditItem;
        /// <summary>
        /// There are no comments for AuditItemContacts in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<AuditItemContacts> AuditItemContacts
        {
            get
            {
                if ((this._AuditItemContacts == null))
                {
                    this._AuditItemContacts = base.CreateQuery<AuditItemContacts>("[AuditItemContacts]");
                }
                return this._AuditItemContacts;
            }
        }
        private global::System.Data.Objects.ObjectQuery<AuditItemContacts> _AuditItemContacts;
        /// <summary>
        /// There are no comments for Incident in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Incident> Incident
        {
            get
            {
                if ((this._Incident == null))
                {
                    this._Incident = base.CreateQuery<Incident>("[Incident]");
                }
                return this._Incident;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Incident> _Incident;
        /// <summary>
        /// There are no comments for IncidentAuditItem in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<IncidentAuditItem> IncidentAuditItem
        {
            get
            {
                if ((this._IncidentAuditItem == null))
                {
                    this._IncidentAuditItem = base.CreateQuery<IncidentAuditItem>("[IncidentAuditItem]");
                }
                return this._IncidentAuditItem;
            }
        }
        private global::System.Data.Objects.ObjectQuery<IncidentAuditItem> _IncidentAuditItem;
        /// <summary>
        /// There are no comments for OtherAuditItem in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<OtherAuditItem> OtherAuditItem
        {
            get
            {
                if ((this._OtherAuditItem == null))
                {
                    this._OtherAuditItem = base.CreateQuery<OtherAuditItem>("[OtherAuditItem]");
                }
                return this._OtherAuditItem;
            }
        }
        private global::System.Data.Objects.ObjectQuery<OtherAuditItem> _OtherAuditItem;
        /// <summary>
        /// There are no comments for AuditItem in the schema.
        /// </summary>
        public void AddToAuditItem(AuditItem auditItem)
        {
            base.AddObject("AuditItem", auditItem);
        }
        /// <summary>
        /// There are no comments for AuditItemContacts in the schema.
        /// </summary>
        public void AddToAuditItemContacts(AuditItemContacts auditItemContacts)
        {
            base.AddObject("AuditItemContacts", auditItemContacts);
        }
        /// <summary>
        /// There are no comments for Incident in the schema.
        /// </summary>
        public void AddToIncident(Incident incident)
        {
            base.AddObject("Incident", incident);
        }
        /// <summary>
        /// There are no comments for IncidentAuditItem in the schema.
        /// </summary>
        public void AddToIncidentAuditItem(IncidentAuditItem incidentAuditItem)
        {
            base.AddObject("IncidentAuditItem", incidentAuditItem);
        }
        /// <summary>
        /// There are no comments for OtherAuditItem in the schema.
        /// </summary>
        public void AddToOtherAuditItem(OtherAuditItem otherAuditItem)
        {
            base.AddObject("OtherAuditItem", otherAuditItem);
        }
    }
    /// <summary>
    /// There are no comments for SIRModel.AuditItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// AuditItemID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SIRModel", Name="AuditItem")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class AuditItem : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new AuditItem object.
        /// </summary>
        /// <param name="auditItemID">Initial value of AuditItemID.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="description">Initial value of Description.</param>
        /// <param name="isActive">Initial value of IsActive.</param>
        /// <param name="createdBy">Initial value of CreatedBy.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        /// <param name="lastModifiedBy">Initial value of LastModifiedBy.</param>
        /// <param name="lastModifiedDate">Initial value of LastModifiedDate.</param>
        public static AuditItem CreateAuditItem(int auditItemID, string name, string description, bool isActive, string createdBy, global::System.DateTime createdDate, string lastModifiedBy, global::System.DateTime lastModifiedDate)
        {
            AuditItem auditItem = new AuditItem();
            auditItem.AuditItemID = auditItemID;
            auditItem.Name = name;
            auditItem.Description = description;
            auditItem.IsActive = isActive;
            auditItem.CreatedBy = createdBy;
            auditItem.CreatedDate = createdDate;
            auditItem.LastModifiedBy = lastModifiedBy;
            auditItem.LastModifiedDate = lastModifiedDate;
            return auditItem;
        }
        /// <summary>
        /// There are no comments for Property AuditItemID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int AuditItemID
        {
            get
            {
                return this._AuditItemID;
            }
            set
            {
                this.OnAuditItemIDChanging(value);
                this.ReportPropertyChanging("AuditItemID");
                this._AuditItemID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AuditItemID");
                this.OnAuditItemIDChanged();
            }
        }
        private int _AuditItemID;
        partial void OnAuditItemIDChanging(int value);
        partial void OnAuditItemIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property IsActive in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this.OnIsActiveChanging(value);
                this.ReportPropertyChanging("IsActive");
                this._IsActive = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsActive");
                this.OnIsActiveChanged();
            }
        }
        private bool _IsActive;
        partial void OnIsActiveChanging(bool value);
        partial void OnIsActiveChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this.ReportPropertyChanging("CreatedBy");
                this._CreatedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CreatedBy");
                this.OnCreatedByChanged();
            }
        }
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this.ReportPropertyChanging("CreatedDate");
                this._CreatedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreatedDate");
                this.OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Property LastModifiedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LastModifiedBy
        {
            get
            {
                return this._LastModifiedBy;
            }
            set
            {
                this.OnLastModifiedByChanging(value);
                this.ReportPropertyChanging("LastModifiedBy");
                this._LastModifiedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("LastModifiedBy");
                this.OnLastModifiedByChanged();
            }
        }
        private string _LastModifiedBy;
        partial void OnLastModifiedByChanging(string value);
        partial void OnLastModifiedByChanged();
        /// <summary>
        /// There are no comments for Property LastModifiedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime LastModifiedDate
        {
            get
            {
                return this._LastModifiedDate;
            }
            set
            {
                this.OnLastModifiedDateChanging(value);
                this.ReportPropertyChanging("LastModifiedDate");
                this._LastModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LastModifiedDate");
                this.OnLastModifiedDateChanged();
            }
        }
        private global::System.DateTime _LastModifiedDate;
        partial void OnLastModifiedDateChanging(global::System.DateTime value);
        partial void OnLastModifiedDateChanged();
        /// <summary>
        /// There are no comments for IncidentAuditItem in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SIRModel", "FK_IncidentAuditItem_AuditItem", "IncidentAuditItem")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<IncidentAuditItem> IncidentAuditItem
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<IncidentAuditItem>("SIRModel.FK_IncidentAuditItem_AuditItem", "IncidentAuditItem");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<IncidentAuditItem>("SIRModel.FK_IncidentAuditItem_AuditItem", "IncidentAuditItem", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for SIRModel.AuditItemContacts in the schema.
    /// </summary>
    /// <KeyProperties>
    /// AuditItemContactID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SIRModel", Name="AuditItemContacts")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class AuditItemContacts : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new AuditItemContacts object.
        /// </summary>
        /// <param name="auditItemContactID">Initial value of AuditItemContactID.</param>
        /// <param name="auditItemID">Initial value of AuditItemID.</param>
        /// <param name="auditItemContactName">Initial value of AuditItemContactName.</param>
        /// <param name="auditItemContactEmail">Initial value of AuditItemContactEmail.</param>
        /// <param name="description">Initial value of Description.</param>
        /// <param name="isActive">Initial value of IsActive.</param>
        /// <param name="createdBy">Initial value of CreatedBy.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        /// <param name="lastModifiedBy">Initial value of LastModifiedBy.</param>
        /// <param name="lastModifiedDate">Initial value of LastModifiedDate.</param>
        public static AuditItemContacts CreateAuditItemContacts(int auditItemContactID, int auditItemID, string auditItemContactName, string auditItemContactEmail, string description, bool isActive, string createdBy, global::System.DateTime createdDate, string lastModifiedBy, global::System.DateTime lastModifiedDate)
        {
            AuditItemContacts auditItemContacts = new AuditItemContacts();
            auditItemContacts.AuditItemContactID = auditItemContactID;
            auditItemContacts.AuditItemID = auditItemID;
            auditItemContacts.AuditItemContactName = auditItemContactName;
            auditItemContacts.AuditItemContactEmail = auditItemContactEmail;
            auditItemContacts.Description = description;
            auditItemContacts.IsActive = isActive;
            auditItemContacts.CreatedBy = createdBy;
            auditItemContacts.CreatedDate = createdDate;
            auditItemContacts.LastModifiedBy = lastModifiedBy;
            auditItemContacts.LastModifiedDate = lastModifiedDate;
            return auditItemContacts;
        }
        /// <summary>
        /// There are no comments for Property AuditItemContactID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int AuditItemContactID
        {
            get
            {
                return this._AuditItemContactID;
            }
            set
            {
                this.OnAuditItemContactIDChanging(value);
                this.ReportPropertyChanging("AuditItemContactID");
                this._AuditItemContactID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AuditItemContactID");
                this.OnAuditItemContactIDChanged();
            }
        }
        private int _AuditItemContactID;
        partial void OnAuditItemContactIDChanging(int value);
        partial void OnAuditItemContactIDChanged();
        /// <summary>
        /// There are no comments for Property AuditItemID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int AuditItemID
        {
            get
            {
                return this._AuditItemID;
            }
            set
            {
                this.OnAuditItemIDChanging(value);
                this.ReportPropertyChanging("AuditItemID");
                this._AuditItemID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AuditItemID");
                this.OnAuditItemIDChanged();
            }
        }
        private int _AuditItemID;
        partial void OnAuditItemIDChanging(int value);
        partial void OnAuditItemIDChanged();
        /// <summary>
        /// There are no comments for Property AuditItemContactName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string AuditItemContactName
        {
            get
            {
                return this._AuditItemContactName;
            }
            set
            {
                this.OnAuditItemContactNameChanging(value);
                this.ReportPropertyChanging("AuditItemContactName");
                this._AuditItemContactName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("AuditItemContactName");
                this.OnAuditItemContactNameChanged();
            }
        }
        private string _AuditItemContactName;
        partial void OnAuditItemContactNameChanging(string value);
        partial void OnAuditItemContactNameChanged();
        /// <summary>
        /// There are no comments for Property AuditItemContactEmail in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string AuditItemContactEmail
        {
            get
            {
                return this._AuditItemContactEmail;
            }
            set
            {
                this.OnAuditItemContactEmailChanging(value);
                this.ReportPropertyChanging("AuditItemContactEmail");
                this._AuditItemContactEmail = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("AuditItemContactEmail");
                this.OnAuditItemContactEmailChanged();
            }
        }
        private string _AuditItemContactEmail;
        partial void OnAuditItemContactEmailChanging(string value);
        partial void OnAuditItemContactEmailChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property IsActive in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this.OnIsActiveChanging(value);
                this.ReportPropertyChanging("IsActive");
                this._IsActive = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsActive");
                this.OnIsActiveChanged();
            }
        }
        private bool _IsActive;
        partial void OnIsActiveChanging(bool value);
        partial void OnIsActiveChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this.ReportPropertyChanging("CreatedBy");
                this._CreatedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CreatedBy");
                this.OnCreatedByChanged();
            }
        }
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this.ReportPropertyChanging("CreatedDate");
                this._CreatedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreatedDate");
                this.OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Property LastModifiedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LastModifiedBy
        {
            get
            {
                return this._LastModifiedBy;
            }
            set
            {
                this.OnLastModifiedByChanging(value);
                this.ReportPropertyChanging("LastModifiedBy");
                this._LastModifiedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("LastModifiedBy");
                this.OnLastModifiedByChanged();
            }
        }
        private string _LastModifiedBy;
        partial void OnLastModifiedByChanging(string value);
        partial void OnLastModifiedByChanged();
        /// <summary>
        /// There are no comments for Property LastModifiedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime LastModifiedDate
        {
            get
            {
                return this._LastModifiedDate;
            }
            set
            {
                this.OnLastModifiedDateChanging(value);
                this.ReportPropertyChanging("LastModifiedDate");
                this._LastModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LastModifiedDate");
                this.OnLastModifiedDateChanged();
            }
        }
        private global::System.DateTime _LastModifiedDate;
        partial void OnLastModifiedDateChanging(global::System.DateTime value);
        partial void OnLastModifiedDateChanged();
    }
    /// <summary>
    /// There are no comments for SIRModel.Incident in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IncidentID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SIRModel", Name="Incident")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Incident : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Incident object.
        /// </summary>
        /// <param name="incidentID">Initial value of IncidentID.</param>
        /// <param name="incidentNumber">Initial value of IncidentNumber.</param>
        /// <param name="heatTicketNumber">Initial value of HeatTicketNumber.</param>
        /// <param name="technicianName">Initial value of TechnicianName.</param>
        /// <param name="technicianEmail">Initial value of TechnicianEmail.</param>
        /// <param name="technicianPhone">Initial value of TechnicianPhone.</param>
        /// <param name="serviceGroupID">Initial value of ServiceGroupID.</param>
        /// <param name="issueStartDate">Initial value of IssueStartDate.</param>
        /// <param name="issueResolutionDate">Initial value of IssueResolutionDate.</param>
        /// <param name="issueDeviceID">Initial value of IssueDeviceID.</param>
        /// <param name="issueLocation">Initial value of IssueLocation.</param>
        /// <param name="issueDescription">Initial value of IssueDescription.</param>
        /// <param name="issueSummary">Initial value of IssueSummary.</param>
        /// <param name="issueChronology">Initial value of IssueChronology.</param>
        /// <param name="issueRootCause">Initial value of IssueRootCause.</param>
        /// <param name="processImprovements">Initial value of ProcessImprovements.</param>
        /// <param name="otherSystemsAffected">Initial value of OtherSystemsAffected.</param>
        /// <param name="travelRequired">Initial value of TravelRequired.</param>
        /// <param name="severityID">Initial value of SeverityID.</param>
        /// <param name="impactID">Initial value of ImpactID.</param>
        /// <param name="visibilityID">Initial value of VisibilityID.</param>
        /// <param name="status">Initial value of Status.</param>
        /// <param name="reportID">Initial value of ReportID.</param>
        /// <param name="createdBy">Initial value of CreatedBy.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        /// <param name="lastModifiedBy">Initial value of LastModifiedBy.</param>
        /// <param name="lastModifiedDate">Initial value of LastModifiedDate.</param>
        public static Incident CreateIncident(
                    global::System.Guid incidentID, 
                    string incidentNumber, 
                    string heatTicketNumber, 
                    string technicianName, 
                    string technicianEmail, 
                    string technicianPhone, 
                    int serviceGroupID, 
                    global::System.DateTime issueStartDate, 
                    global::System.DateTime issueResolutionDate, 
                    string issueDeviceID, 
                    string issueLocation, 
                    string issueDescription, 
                    string issueSummary, 
                    string issueChronology, 
                    string issueRootCause, 
                    string processImprovements, 
                    bool otherSystemsAffected, 
                    bool travelRequired, 
                    int severityID, 
                    int impactID, 
                    int visibilityID, 
                    string status, 
                    int reportID, 
                    string createdBy, 
                    global::System.DateTime createdDate, 
                    string lastModifiedBy, 
                    global::System.DateTime lastModifiedDate)
        {
            Incident incident = new Incident();
            incident.IncidentID = incidentID;
            incident.IncidentNumber = incidentNumber;
            incident.HeatTicketNumber = heatTicketNumber;
            incident.TechnicianName = technicianName;
            incident.TechnicianEmail = technicianEmail;
            incident.TechnicianPhone = technicianPhone;
            incident.ServiceGroupID = serviceGroupID;
            incident.IssueStartDate = issueStartDate;
            incident.IssueResolutionDate = issueResolutionDate;
            incident.IssueDeviceID = issueDeviceID;
            incident.IssueLocation = issueLocation;
            incident.IssueDescription = issueDescription;
            incident.IssueSummary = issueSummary;
            incident.IssueChronology = issueChronology;
            incident.IssueRootCause = issueRootCause;
            incident.ProcessImprovements = processImprovements;
            incident.OtherSystemsAffected = otherSystemsAffected;
            incident.TravelRequired = travelRequired;
            incident.SeverityID = severityID;
            incident.ImpactID = impactID;
            incident.VisibilityID = visibilityID;
            incident.Status = status;
            incident.ReportID = reportID;
            incident.CreatedBy = createdBy;
            incident.CreatedDate = createdDate;
            incident.LastModifiedBy = lastModifiedBy;
            incident.LastModifiedDate = lastModifiedDate;
            return incident;
        }
        /// <summary>
        /// There are no comments for Property IncidentID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid IncidentID
        {
            get
            {
                return this._IncidentID;
            }
            set
            {
                this.OnIncidentIDChanging(value);
                this.ReportPropertyChanging("IncidentID");
                this._IncidentID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IncidentID");
                this.OnIncidentIDChanged();
            }
        }
        private global::System.Guid _IncidentID;
        partial void OnIncidentIDChanging(global::System.Guid value);
        partial void OnIncidentIDChanged();
        /// <summary>
        /// There are no comments for Property IncidentNumber in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string IncidentNumber
        {
            get
            {
                return this._IncidentNumber;
            }
            set
            {
                this.OnIncidentNumberChanging(value);
                this.ReportPropertyChanging("IncidentNumber");
                this._IncidentNumber = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("IncidentNumber");
                this.OnIncidentNumberChanged();
            }
        }
        private string _IncidentNumber;
        partial void OnIncidentNumberChanging(string value);
        partial void OnIncidentNumberChanged();
        /// <summary>
        /// There are no comments for Property HeatTicketNumber in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string HeatTicketNumber
        {
            get
            {
                return this._HeatTicketNumber;
            }
            set
            {
                this.OnHeatTicketNumberChanging(value);
                this.ReportPropertyChanging("HeatTicketNumber");
                this._HeatTicketNumber = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("HeatTicketNumber");
                this.OnHeatTicketNumberChanged();
            }
        }
        private string _HeatTicketNumber;
        partial void OnHeatTicketNumberChanging(string value);
        partial void OnHeatTicketNumberChanged();
        /// <summary>
        /// There are no comments for Property ChangeRequestNumber in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ChangeRequestNumber
        {
            get
            {
                return this._ChangeRequestNumber;
            }
            set
            {
                this.OnChangeRequestNumberChanging(value);
                this.ReportPropertyChanging("ChangeRequestNumber");
                this._ChangeRequestNumber = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ChangeRequestNumber");
                this.OnChangeRequestNumberChanged();
            }
        }
        private string _ChangeRequestNumber;
        partial void OnChangeRequestNumberChanging(string value);
        partial void OnChangeRequestNumberChanged();
        /// <summary>
        /// There are no comments for Property ServiceDeskTicketNumber in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceDeskTicketNumber
        {
            get
            {
                return this._ServiceDeskTicketNumber;
            }
            set
            {
                this.OnServiceDeskTicketNumberChanging(value);
                this.ReportPropertyChanging("ServiceDeskTicketNumber");
                this._ServiceDeskTicketNumber = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("ServiceDeskTicketNumber");
                this.OnServiceDeskTicketNumberChanged();
            }
        }
        private string _ServiceDeskTicketNumber;
        partial void OnServiceDeskTicketNumberChanging(string value);
        partial void OnServiceDeskTicketNumberChanged();
        /// <summary>
        /// There are no comments for Property TechnicianName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string TechnicianName
        {
            get
            {
                return this._TechnicianName;
            }
            set
            {
                this.OnTechnicianNameChanging(value);
                this.ReportPropertyChanging("TechnicianName");
                this._TechnicianName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("TechnicianName");
                this.OnTechnicianNameChanged();
            }
        }
        private string _TechnicianName;
        partial void OnTechnicianNameChanging(string value);
        partial void OnTechnicianNameChanged();
        /// <summary>
        /// There are no comments for Property TechnicianEmail in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string TechnicianEmail
        {
            get
            {
                return this._TechnicianEmail;
            }
            set
            {
                this.OnTechnicianEmailChanging(value);
                this.ReportPropertyChanging("TechnicianEmail");
                this._TechnicianEmail = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("TechnicianEmail");
                this.OnTechnicianEmailChanged();
            }
        }
        private string _TechnicianEmail;
        partial void OnTechnicianEmailChanging(string value);
        partial void OnTechnicianEmailChanged();
        /// <summary>
        /// There are no comments for Property TechnicianPhone in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string TechnicianPhone
        {
            get
            {
                return this._TechnicianPhone;
            }
            set
            {
                this.OnTechnicianPhoneChanging(value);
                this.ReportPropertyChanging("TechnicianPhone");
                this._TechnicianPhone = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("TechnicianPhone");
                this.OnTechnicianPhoneChanged();
            }
        }
        private string _TechnicianPhone;
        partial void OnTechnicianPhoneChanging(string value);
        partial void OnTechnicianPhoneChanged();
        /// <summary>
        /// There are no comments for Property ServiceGroupID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ServiceGroupID
        {
            get
            {
                return this._ServiceGroupID;
            }
            set
            {
                this.OnServiceGroupIDChanging(value);
                this.ReportPropertyChanging("ServiceGroupID");
                this._ServiceGroupID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ServiceGroupID");
                this.OnServiceGroupIDChanged();
            }
        }
        private int _ServiceGroupID;
        partial void OnServiceGroupIDChanging(int value);
        partial void OnServiceGroupIDChanged();
        /// <summary>
        /// There are no comments for Property IssueStartDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime IssueStartDate
        {
            get
            {
                return this._IssueStartDate;
            }
            set
            {
                this.OnIssueStartDateChanging(value);
                this.ReportPropertyChanging("IssueStartDate");
                this._IssueStartDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IssueStartDate");
                this.OnIssueStartDateChanged();
            }
        }
        private global::System.DateTime _IssueStartDate;
        partial void OnIssueStartDateChanging(global::System.DateTime value);
        partial void OnIssueStartDateChanged();
        /// <summary>
        /// There are no comments for Property IssueResolutionDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime IssueResolutionDate
        {
            get
            {
                return this._IssueResolutionDate;
            }
            set
            {
                this.OnIssueResolutionDateChanging(value);
                this.ReportPropertyChanging("IssueResolutionDate");
                this._IssueResolutionDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IssueResolutionDate");
                this.OnIssueResolutionDateChanged();
            }
        }
        private global::System.DateTime _IssueResolutionDate;
        partial void OnIssueResolutionDateChanging(global::System.DateTime value);
        partial void OnIssueResolutionDateChanged();
        /// <summary>
        /// There are no comments for Property IssueDeviceID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string IssueDeviceID
        {
            get
            {
                return this._IssueDeviceID;
            }
            set
            {
                this.OnIssueDeviceIDChanging(value);
                this.ReportPropertyChanging("IssueDeviceID");
                this._IssueDeviceID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("IssueDeviceID");
                this.OnIssueDeviceIDChanged();
            }
        }
        private string _IssueDeviceID;
        partial void OnIssueDeviceIDChanging(string value);
        partial void OnIssueDeviceIDChanged();
        /// <summary>
        /// There are no comments for Property IssueLocation in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string IssueLocation
        {
            get
            {
                return this._IssueLocation;
            }
            set
            {
                this.OnIssueLocationChanging(value);
                this.ReportPropertyChanging("IssueLocation");
                this._IssueLocation = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("IssueLocation");
                this.OnIssueLocationChanged();
            }
        }
        private string _IssueLocation;
        partial void OnIssueLocationChanging(string value);
        partial void OnIssueLocationChanged();
        /// <summary>
        /// There are no comments for Property IssueDescription in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string IssueDescription
        {
            get
            {
                return this._IssueDescription;
            }
            set
            {
                this.OnIssueDescriptionChanging(value);
                this.ReportPropertyChanging("IssueDescription");
                this._IssueDescription = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("IssueDescription");
                this.OnIssueDescriptionChanged();
            }
        }
        private string _IssueDescription;
        partial void OnIssueDescriptionChanging(string value);
        partial void OnIssueDescriptionChanged();
        /// <summary>
        /// There are no comments for Property IssueSummary in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string IssueSummary
        {
            get
            {
                return this._IssueSummary;
            }
            set
            {
                this.OnIssueSummaryChanging(value);
                this.ReportPropertyChanging("IssueSummary");
                this._IssueSummary = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("IssueSummary");
                this.OnIssueSummaryChanged();
            }
        }
        private string _IssueSummary;
        partial void OnIssueSummaryChanging(string value);
        partial void OnIssueSummaryChanged();
        /// <summary>
        /// There are no comments for Property IssueChronology in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string IssueChronology
        {
            get
            {
                return this._IssueChronology;
            }
            set
            {
                this.OnIssueChronologyChanging(value);
                this.ReportPropertyChanging("IssueChronology");
                this._IssueChronology = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("IssueChronology");
                this.OnIssueChronologyChanged();
            }
        }
        private string _IssueChronology;
        partial void OnIssueChronologyChanging(string value);
        partial void OnIssueChronologyChanged();
        /// <summary>
        /// There are no comments for Property IssueRootCause in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string IssueRootCause
        {
            get
            {
                return this._IssueRootCause;
            }
            set
            {
                this.OnIssueRootCauseChanging(value);
                this.ReportPropertyChanging("IssueRootCause");
                this._IssueRootCause = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("IssueRootCause");
                this.OnIssueRootCauseChanged();
            }
        }
        private string _IssueRootCause;
        partial void OnIssueRootCauseChanging(string value);
        partial void OnIssueRootCauseChanged();
        /// <summary>
        /// There are no comments for Property ProcessImprovements in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessImprovements
        {
            get
            {
                return this._ProcessImprovements;
            }
            set
            {
                this.OnProcessImprovementsChanging(value);
                this.ReportPropertyChanging("ProcessImprovements");
                this._ProcessImprovements = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ProcessImprovements");
                this.OnProcessImprovementsChanged();
            }
        }
        private string _ProcessImprovements;
        partial void OnProcessImprovementsChanging(string value);
        partial void OnProcessImprovementsChanged();
        /// <summary>
        /// There are no comments for Property OtherSystemsAffected in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool OtherSystemsAffected
        {
            get
            {
                return this._OtherSystemsAffected;
            }
            set
            {
                this.OnOtherSystemsAffectedChanging(value);
                this.ReportPropertyChanging("OtherSystemsAffected");
                this._OtherSystemsAffected = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("OtherSystemsAffected");
                this.OnOtherSystemsAffectedChanged();
            }
        }
        private bool _OtherSystemsAffected;
        partial void OnOtherSystemsAffectedChanging(bool value);
        partial void OnOtherSystemsAffectedChanged();
        /// <summary>
        /// There are no comments for Property OtherSystemsAffectedValue in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string OtherSystemsAffectedValue
        {
            get
            {
                return this._OtherSystemsAffectedValue;
            }
            set
            {
                this.OnOtherSystemsAffectedValueChanging(value);
                this.ReportPropertyChanging("OtherSystemsAffectedValue");
                this._OtherSystemsAffectedValue = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("OtherSystemsAffectedValue");
                this.OnOtherSystemsAffectedValueChanged();
            }
        }
        private string _OtherSystemsAffectedValue;
        partial void OnOtherSystemsAffectedValueChanging(string value);
        partial void OnOtherSystemsAffectedValueChanged();
        /// <summary>
        /// There are no comments for Property TravelRequired in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool TravelRequired
        {
            get
            {
                return this._TravelRequired;
            }
            set
            {
                this.OnTravelRequiredChanging(value);
                this.ReportPropertyChanging("TravelRequired");
                this._TravelRequired = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TravelRequired");
                this.OnTravelRequiredChanged();
            }
        }
        private bool _TravelRequired;
        partial void OnTravelRequiredChanging(bool value);
        partial void OnTravelRequiredChanged();
        /// <summary>
        /// There are no comments for Property SeverityID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int SeverityID
        {
            get
            {
                return this._SeverityID;
            }
            set
            {
                this.OnSeverityIDChanging(value);
                this.ReportPropertyChanging("SeverityID");
                this._SeverityID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SeverityID");
                this.OnSeverityIDChanged();
            }
        }
        private int _SeverityID;
        partial void OnSeverityIDChanging(int value);
        partial void OnSeverityIDChanged();
        /// <summary>
        /// There are no comments for Property ImpactID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ImpactID
        {
            get
            {
                return this._ImpactID;
            }
            set
            {
                this.OnImpactIDChanging(value);
                this.ReportPropertyChanging("ImpactID");
                this._ImpactID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ImpactID");
                this.OnImpactIDChanged();
            }
        }
        private int _ImpactID;
        partial void OnImpactIDChanging(int value);
        partial void OnImpactIDChanged();
        /// <summary>
        /// There are no comments for Property VisibilityID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int VisibilityID
        {
            get
            {
                return this._VisibilityID;
            }
            set
            {
                this.OnVisibilityIDChanging(value);
                this.ReportPropertyChanging("VisibilityID");
                this._VisibilityID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("VisibilityID");
                this.OnVisibilityIDChanged();
            }
        }
        private int _VisibilityID;
        partial void OnVisibilityIDChanging(int value);
        partial void OnVisibilityIDChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this.ReportPropertyChanging("Status");
                this._Status = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Status");
                this.OnStatusChanged();
            }
        }
        private string _Status;
        partial void OnStatusChanging(string value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property ReportID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ReportID
        {
            get
            {
                return this._ReportID;
            }
            set
            {
                this.OnReportIDChanging(value);
                this.ReportPropertyChanging("ReportID");
                this._ReportID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ReportID");
                this.OnReportIDChanged();
            }
        }
        private int _ReportID;
        partial void OnReportIDChanging(int value);
        partial void OnReportIDChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this.ReportPropertyChanging("CreatedBy");
                this._CreatedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CreatedBy");
                this.OnCreatedByChanged();
            }
        }
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this.ReportPropertyChanging("CreatedDate");
                this._CreatedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreatedDate");
                this.OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Property LastModifiedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LastModifiedBy
        {
            get
            {
                return this._LastModifiedBy;
            }
            set
            {
                this.OnLastModifiedByChanging(value);
                this.ReportPropertyChanging("LastModifiedBy");
                this._LastModifiedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("LastModifiedBy");
                this.OnLastModifiedByChanged();
            }
        }
        private string _LastModifiedBy;
        partial void OnLastModifiedByChanging(string value);
        partial void OnLastModifiedByChanged();
        /// <summary>
        /// There are no comments for Property LastModifiedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime LastModifiedDate
        {
            get
            {
                return this._LastModifiedDate;
            }
            set
            {
                this.OnLastModifiedDateChanging(value);
                this.ReportPropertyChanging("LastModifiedDate");
                this._LastModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LastModifiedDate");
                this.OnLastModifiedDateChanged();
            }
        }
        private global::System.DateTime _LastModifiedDate;
        partial void OnLastModifiedDateChanging(global::System.DateTime value);
        partial void OnLastModifiedDateChanged();
        /// <summary>
        /// There are no comments for IncidentAuditItem in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SIRModel", "FK_IncidentAuditItem_Incident", "IncidentAuditItem")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<IncidentAuditItem> IncidentAuditItem
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<IncidentAuditItem>("SIRModel.FK_IncidentAuditItem_Incident", "IncidentAuditItem");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<IncidentAuditItem>("SIRModel.FK_IncidentAuditItem_Incident", "IncidentAuditItem", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for OtherAuditItem in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SIRModel", "FK_OtherAuditItem_Incident", "OtherAuditItem")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<OtherAuditItem> OtherAuditItem
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<OtherAuditItem>("SIRModel.FK_OtherAuditItem_Incident", "OtherAuditItem");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<OtherAuditItem>("SIRModel.FK_OtherAuditItem_Incident", "OtherAuditItem", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for SIRModel.IncidentAuditItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IncidentID
    /// AuditItemID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SIRModel", Name="IncidentAuditItem")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class IncidentAuditItem : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new IncidentAuditItem object.
        /// </summary>
        /// <param name="incidentID">Initial value of IncidentID.</param>
        /// <param name="auditItemID">Initial value of AuditItemID.</param>
        /// <param name="createdBy">Initial value of CreatedBy.</param>
        /// <param name="createdDate">Initial value of CreatedDate.</param>
        /// <param name="lastModifiedBy">Initial value of LastModifiedBy.</param>
        /// <param name="lastModifiedDate">Initial value of LastModifiedDate.</param>
        public static IncidentAuditItem CreateIncidentAuditItem(global::System.Guid incidentID, int auditItemID, string createdBy, global::System.DateTime createdDate, string lastModifiedBy, global::System.DateTime lastModifiedDate)
        {
            IncidentAuditItem incidentAuditItem = new IncidentAuditItem();
            incidentAuditItem.IncidentID = incidentID;
            incidentAuditItem.AuditItemID = auditItemID;
            incidentAuditItem.CreatedBy = createdBy;
            incidentAuditItem.CreatedDate = createdDate;
            incidentAuditItem.LastModifiedBy = lastModifiedBy;
            incidentAuditItem.LastModifiedDate = lastModifiedDate;
            return incidentAuditItem;
        }
        /// <summary>
        /// There are no comments for Property IncidentID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Guid IncidentID
        {
            get
            {
                return this._IncidentID;
            }
            set
            {
                this.OnIncidentIDChanging(value);
                this.ReportPropertyChanging("IncidentID");
                this._IncidentID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IncidentID");
                this.OnIncidentIDChanged();
            }
        }
        private global::System.Guid _IncidentID;
        partial void OnIncidentIDChanging(global::System.Guid value);
        partial void OnIncidentIDChanged();
        /// <summary>
        /// There are no comments for Property AuditItemID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int AuditItemID
        {
            get
            {
                return this._AuditItemID;
            }
            set
            {
                this.OnAuditItemIDChanging(value);
                this.ReportPropertyChanging("AuditItemID");
                this._AuditItemID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AuditItemID");
                this.OnAuditItemIDChanged();
            }
        }
        private int _AuditItemID;
        partial void OnAuditItemIDChanging(int value);
        partial void OnAuditItemIDChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this.ReportPropertyChanging("CreatedBy");
                this._CreatedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CreatedBy");
                this.OnCreatedByChanged();
            }
        }
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this.ReportPropertyChanging("CreatedDate");
                this._CreatedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreatedDate");
                this.OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Property LastModifiedBy in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LastModifiedBy
        {
            get
            {
                return this._LastModifiedBy;
            }
            set
            {
                this.OnLastModifiedByChanging(value);
                this.ReportPropertyChanging("LastModifiedBy");
                this._LastModifiedBy = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("LastModifiedBy");
                this.OnLastModifiedByChanged();
            }
        }
        private string _LastModifiedBy;
        partial void OnLastModifiedByChanging(string value);
        partial void OnLastModifiedByChanged();
        /// <summary>
        /// There are no comments for Property LastModifiedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime LastModifiedDate
        {
            get
            {
                return this._LastModifiedDate;
            }
            set
            {
                this.OnLastModifiedDateChanging(value);
                this.ReportPropertyChanging("LastModifiedDate");
                this._LastModifiedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LastModifiedDate");
                this.OnLastModifiedDateChanged();
            }
        }
        private global::System.DateTime _LastModifiedDate;
        partial void OnLastModifiedDateChanging(global::System.DateTime value);
        partial void OnLastModifiedDateChanged();
        /// <summary>
        /// There are no comments for AuditItem in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SIRModel", "FK_IncidentAuditItem_AuditItem", "AuditItem")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public AuditItem AuditItem
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<AuditItem>("SIRModel.FK_IncidentAuditItem_AuditItem", "AuditItem").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<AuditItem>("SIRModel.FK_IncidentAuditItem_AuditItem", "AuditItem").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for AuditItem in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<AuditItem> AuditItemReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<AuditItem>("SIRModel.FK_IncidentAuditItem_AuditItem", "AuditItem");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<AuditItem>("SIRModel.FK_IncidentAuditItem_AuditItem", "AuditItem", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Incident in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SIRModel", "FK_IncidentAuditItem_Incident", "Incident")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Incident Incident
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Incident>("SIRModel.FK_IncidentAuditItem_Incident", "Incident").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Incident>("SIRModel.FK_IncidentAuditItem_Incident", "Incident").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Incident in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Incident> IncidentReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Incident>("SIRModel.FK_IncidentAuditItem_Incident", "Incident");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Incident>("SIRModel.FK_IncidentAuditItem_Incident", "Incident", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for SIRModel.OtherAuditItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// OtherAuditItemID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SIRModel", Name="OtherAuditItem")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class OtherAuditItem : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new OtherAuditItem object.
        /// </summary>
        /// <param name="otherAuditItemID">Initial value of OtherAuditItemID.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="email">Initial value of Email.</param>
        public static OtherAuditItem CreateOtherAuditItem(int otherAuditItemID, string name, string email)
        {
            OtherAuditItem otherAuditItem = new OtherAuditItem();
            otherAuditItem.OtherAuditItemID = otherAuditItemID;
            otherAuditItem.Name = name;
            otherAuditItem.Email = email;
            return otherAuditItem;
        }
        /// <summary>
        /// There are no comments for Property OtherAuditItemID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int OtherAuditItemID
        {
            get
            {
                return this._OtherAuditItemID;
            }
            set
            {
                this.OnOtherAuditItemIDChanging(value);
                this.ReportPropertyChanging("OtherAuditItemID");
                this._OtherAuditItemID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("OtherAuditItemID");
                this.OnOtherAuditItemIDChanged();
            }
        }
        private int _OtherAuditItemID;
        partial void OnOtherAuditItemIDChanging(int value);
        partial void OnOtherAuditItemIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this.ReportPropertyChanging("Email");
                this._Email = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Email");
                this.OnEmailChanged();
            }
        }
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Incident in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SIRModel", "FK_OtherAuditItem_Incident", "Incident")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Incident Incident
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Incident>("SIRModel.FK_OtherAuditItem_Incident", "Incident").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Incident>("SIRModel.FK_OtherAuditItem_Incident", "Incident").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Incident in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Incident> IncidentReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Incident>("SIRModel.FK_OtherAuditItem_Incident", "Incident");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Incident>("SIRModel.FK_OtherAuditItem_Incident", "Incident", value);
                }
            }
        }
    }
}
